### PR TITLE
Support ProofGeneral/PG#559 + `C-u C-c C-RET`

### PR DESCRIPTION
**Pull request by erikmd**
* Make company-coq compatible with PR https://github.com/ProofGeneral/PG/pull/559

To reproduce:
* Given company-coq
* and `Proof-General > Quick Options > Processing > Omit Proofs`,
* When doing `C-u C-c C-RET`,
* Then the considered lemmas should be fully processed.

Cc @hendriktews @cpitclaudel

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Thanks a lot!  Reading this a few years later, I wonder if I should have advised that PG function in question instead of rebinding the corresponding key.

**Comment by cpitclaudel** [comment]
I just reverted this, until we merge the PR.

**Comment by erikmd** [comment]
> I just reverted this, until we merge the PR.

@cpitclaudel I just merged https://github.com/ProofGeneral/PG/pull/559;
so you'll be able to revert https://github.com/cpitclaudel/company-coq/commit/6a23da61e4008f54cf1b713f8b8bffd37887e172 when you can (no hurry for that: the fix was not backwards-compatible, but the fix itself is just fixing a minor issue, to some extent :)

**Comment by cpitclaudel** [comment]
https://github.com/cpitclaudel/company-coq/commit/a6e349e0131f676a885bd14c908fd26054b2df42 I think this is a compatible fix?

**Pull request merged**
